In [1]:
A = matrix(c(1, 4, 2, 6, 3, 8), nrow = 3, byrow = TRUE)

In [2]:
C = matrix(c(3, 8, 1, 5, 4, 0), nrow = 2, byrow = TRUE)

In [3]:
print(A %*% C)

     [,1] [,2] [,3]
[1,]   23   24    1
[2,]   36   40    2
[3,]   49   56    3


In [ ]:
#5.4

In [5]:
x <- matrix(c(8,4,0,-4,-8), nrow = 1)
y <- matrix(c(7,8,9.0,10.2,11.0,11.7),nrow = 1)
print(t(y) %*% y)

     [,1] [,2]  [,3]   [,4]  [,5]   [,6]
[1,] 49.0 56.0  63.0  71.40  77.0  81.90
[2,] 56.0 64.0  72.0  81.60  88.0  93.60
[3,] 63.0 72.0  81.0  91.80  99.0 105.30
[4,] 71.4 81.6  91.8 104.04 112.2 119.34
[5,] 77.0 88.0  99.0 112.20 121.0 128.70
[6,] 81.9 93.6 105.3 119.34 128.7 136.89


In [7]:
print(t(x) %*% x)

     [,1] [,2] [,3] [,4] [,5]
[1,]   64   32    0  -32  -64
[2,]   32   16    0  -16  -32
[3,]    0    0    0    0    0
[4,]  -32  -16    0   16   32
[5,]  -64  -32    0   32   64


In [8]:
print(t(x) %*% y)

     [,1] [,2] [,3]  [,4] [,5]  [,6]
[1,]   56   64   72  81.6   88  93.6
[2,]   28   32   36  40.8   44  46.8
[3,]    0    0    0   0.0    0   0.0
[4,]  -28  -32  -36 -40.8  -44 -46.8
[5,]  -56  -64  -72 -81.6  -88 -93.6
